# Generated by Django 3.2.5 on 2021-07-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='pig',
        ),
    ]
